package repository

var (
	PropertyRepository           = new(propertyRepository)
	UserRepository               = new(userRepository)
	UserGroupRepository          = new(userGroupRepository)
	UserGroupMemberRepository    = new(userGroupMemberRepository)
	AssetRepository              = new(assetRepository)
	CredentialRepository         = new(credentialRepository)
	CommandRepository            = new(commandRepository)
	SessionRepository            = new(sessionRepository)
	SecurityRepository           = new(securityRepository)
	GatewayRepository            = new(gatewayRepository)
	JobRepository                = new(jobRepository)
	JobLogRepository             = new(jobLogRepository)
	LoginLogRepository           = new(loginLogRepository)
	StorageRepository            = new(storageRepository)
	StrategyRepository           = new(strategyRepository)
	AccessTokenRepository        = new(accessTokenRepository)
	ShareSessionRepository       = new(shareSessionRepository)
	TenantRepository             = new(tenantRepository)
	RoleRepository               = new(roleRepository)
	UserRoleRefRepository        = new(userRoleRefRepository)
	LoginPolicyRepository        = new(loginPolicyRepository)
	LoginPolicyUserRefRepository = new(loginPolicyUserRefRepository)
	TimePeriodRepository         = new(timePeriodRepository)
	CommandFilterRepository      = new(commandFilterRepository)
	CommandFilterRuleRepository  = new(commandFilterRuleRepository)
	SessionCommandRepository     = new(sessionCommandRepository)
	StorageLogRepository         = new(storageLogRepository)
	AuthorisedRepository         = new(authorisedRepository)
)
